### ISSUE TITLE
Bounce is wrong in the top right corner

### ISSUE THREAD

**Issue by emmanash** [pebblecode/wfh-frontend#1]
The bounce looks bit wrong in the top right corner:

- when I hover over the second-to-last person on the top row (the 8th person), the icon bounces down and left (it should bounce just downwards
- when I hover over the last person on the top row (the 9th person), the icon moves rightwards (it should move down and left)

I think things were hardcoded for the pebble screen this was designed to run on for the hackday, where the rows were 8 icons wide.

**Comment by mikeljames** [comment]
We're currently reconsidering the benefit of this animation, what does it actually solve?

We're currently going through a re-design which may not consider this animation in the next major release.
