### ISSUE TITLE
New category: Remote Worker

### ISSUE THREAD

**Issue by tanepiper** [pebblecode/wfh-frontend#5]
A) We're missing Joe from the list
B) With him and James Wallace, they should be permanently marked as "Remote Worker" with their default status and show as such on the WFH front end.

Remote Worker state dictates that they do not work in the office at all, but can provide a /wfo state when they are in.

**Comment by mikeljames** [comment]
Joe needs to opt-in by using /wfo or /wfh

with Joe and James being remote all the time they just need to update their default status, i.e. the status to fallback to day after day. 

to do this:

`/wfh default:wfh`
